
HunyuanVideo-T2V-720P:
    model_type: T2V
    download_way:
        ms:
            basic_dir: models
            files:
                diffusion_models/hunyuan_video_t2v_720p_bf16.safetensors: Comfy-Org/HunyuanVideo_repackaged/split_files/diffusion_models/hunyuan_video_t2v_720p_bf16.safetensors
                text_encoders/clip_l.safetensors: Comfy-Org/HunyuanVideo_repackaged/split_files/text_encoders/clip_l.safetensors
                text_encoders/llava_llama3_fp16.safetensors: Comfy-Org/HunyuanVideo_repackaged/split_files/text_encoders/llava_llama3_fp16.safetensors
                vae/hunyuan_video_vae_bf16.safetensors: Comfy-Org/HunyuanVideo_repackaged/split_files/vae/hunyuan_video_vae_bf16.safetensors
        cg:
            basic_dir: models
            files:
                diffusion_models/hunyuan_video_t2v_720p_bf16.safetensors: nahz202/hunyuan_video/hunyuan_video_t2v_720p_bf16.safetensors
                text_encoders/clip_l.safetensors: nahz202/hunyuan_video/clip_l.safetensors
                text_encoders/llava_llama3_fp16.safetensors: nahz202/hunyuan_video/llava_llama3_fp16.safetensors
                vae/hunyuan_video_vae_bf16.safetensors: nahz202/hunyuan_video/hunyuan_video_vae_bf16.safetensors
            
    resolution_list: [960x544, 544x960, 832x624, 624x832, 720x720, 960x960, 832x1104, 1104x832, 1280x720, 720x1280]