
HunyuanVideo-T2V-720P:
    model_type: T2V
    model_dl:
        dl_way: ms
        repo_id: Comfy-Org/HunyuanVideo_repackaged
        basic_dir: models
        files:
            diffusion_models/hunyuan_video_t2v_720p_bf16.safetensors: split_files/diffusion_models/hunyuan_video_t2v_720p_bf16.safetensors
            text_encoders/clip_l.safetensors: split_files/text_encoders/clip_l.safetensors
            text_encoders/llava_llama3_fp16.safetensors: split_files/text_encoders/llava_llama3_fp16.safetensors
            vae/hunyuan_video_vae_bf16.safetensors: split_files/vae/hunyuan_video_vae_bf16.safetensors
            
    resolution_list: [960x544, 544x960, 832x624, 624x832, 720x720, 960x960, 832x1104, 1104x832, 1280x720, 720x1280]